export interface OfficialTopic {
  id: string;
  subjectName: string;
  topicCode: string;
  title: string;
  normalizedTitle: string;
  orderIndex: number;
  weight: number;
}

export const OFFICIAL_TOPICS: OfficialTopic[] = [
  // LÍNGUA PORTUGUESA
  {
    id: "portuguese_t0",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 00",
    title: "Ortografia oficial. Acentuação gráfica.",
    normalizedTitle: "ortografia oficial acentuacao grafica",
    orderIndex: 0,
    weight: 1.0,
  },
  {
    id: "portuguese_t1",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 01",
    title: "Classes de palavras I: substantivo, adjetivo, advérbios, artigo, numeral, interjeição.",
    normalizedTitle: "classes de palavras substantivo adjetivo adverbios artigo numeral interjeicao",
    orderIndex: 1,
    weight: 1.0,
  },
  {
    id: "portuguese_t2",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 02",
    title: "Classes de palavras II: preposição e conjunção.",
    normalizedTitle: "classes de palavras preposicao conjuncao",
    orderIndex: 2,
    weight: 1.0,
  },
  {
    id: "portuguese_t3",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 03",
    title: "Classes de palavras III: pronomes. Colocação pronominal.",
    normalizedTitle: "classes de palavras pronomes colocacao pronominal",
    orderIndex: 3,
    weight: 1.0,
  },
  {
    id: "portuguese_t4",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 04",
    title: "Classes de palavras IV: verbos.",
    normalizedTitle: "classes de palavras verbos",
    orderIndex: 4,
    weight: 1.0,
  },
  {
    id: "portuguese_t5",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 05",
    title: "Correlação e vozes verbais.",
    normalizedTitle: "correlacao vozes verbais",
    orderIndex: 5,
    weight: 1.0,
  },
  {
    id: "portuguese_t6",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 06",
    title: "Formação de palavras.",
    normalizedTitle: "formacao de palavras",
    orderIndex: 6,
    weight: 1.0,
  },
  {
    id: "portuguese_t7",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 07",
    title: "Sintaxe da oração: termos da oração.",
    normalizedTitle: "sintaxe da oracao termos da oracao",
    orderIndex: 7,
    weight: 1.0,
  },
  {
    id: "portuguese_t8",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 08",
    title: "Relações de coordenação entre orações e entre termos da oração.",
    normalizedTitle: "relacoes de coordenacao entre oracoes entre termos da oracao",
    orderIndex: 8,
    weight: 1.0,
  },
  {
    id: "portuguese_t9",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 09",
    title: "Pontuação.",
    normalizedTitle: "pontuacao",
    orderIndex: 9,
    weight: 1.0,
  },
  {
    id: "portuguese_t10",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 10",
    title: "Concordância Verbal e Nominal.",
    normalizedTitle: "concordancia verbal nominal",
    orderIndex: 10,
    weight: 1.0,
  },
  {
    id: "portuguese_t11",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 11",
    title: "Regência verbal e nominal. Crase.",
    normalizedTitle: "regencia verbal nominal crase",
    orderIndex: 11,
    weight: 1.0,
  },
  {
    id: "portuguese_t12",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 12",
    title: "Mecanismos de coesão e coerência textuais.",
    normalizedTitle: "mecanismos de coesao coerencia textuais",
    orderIndex: 12,
    weight: 1.0,
  },
  {
    id: "portuguese_t13",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 13",
    title: "Semântica. Significação das palavras.",
    normalizedTitle: "semantica significacao das palavras",
    orderIndex: 13,
    weight: 1.0,
  },
  {
    id: "portuguese_t14",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 14",
    title: "Compreensão e interpretação de textos. Tipologia textual. Funções da linguagem.",
    normalizedTitle: "compreensao interpretacao de textos tipologia textual funcoes da linguagem",
    orderIndex: 14,
    weight: 1.0,
  },
  {
    id: "portuguese_t15",
    subjectName: "Língua Portuguesa",
    topicCode: "Tópico 15",
    title: "Variação linguística.",
    normalizedTitle: "variacao linguistica",
    orderIndex: 15,
    weight: 1.0,
  },

  // DIREITO ADMINISTRATIVO
  {
    id: "admin_t0",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 00",
    title: "Princípios administrativos. Regime jurídico-administrativo.",
    normalizedTitle: "principios administrativos regime juridico administrativo expressos implicitos da administracao publica",
    orderIndex: 0,
    weight: 1.2,
  },
  {
    id: "admin_t1",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 01",
    title: "Introdução ao direito administrativo. Estado, governo e administração pública.",
    normalizedTitle: "introducao direito administrativo estado governo administracao publica",
    orderIndex: 1,
    weight: 1.2,
  },
  {
    id: "admin_t2",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 02",
    title: "Organização administrativa. Administração direta e indireta. Autarquias. Agências.",
    normalizedTitle: "organizacao administrativa administracao direta indireta autarquias agencias",
    orderIndex: 2,
    weight: 1.2,
  },
  {
    id: "admin_t3",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 03",
    title: "Fundações públicas. Empresas públicas. Sociedades de economia mista.",
    normalizedTitle: "fundacoes publicas empresas publicas sociedades de economia mista",
    orderIndex: 3,
    weight: 1.2,
  },
  {
    id: "admin_t4",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 04",
    title: "Entidades paraestatais e terceiro setor.",
    normalizedTitle: "entidades paraestatais terceiro setor",
    orderIndex: 4,
    weight: 1.2,
  },
  {
    id: "admin_t5",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 05",
    title: "Poderes e deveres da Administração Pública.",
    normalizedTitle: "poderes deveres da administracao publica discricionario vinculado hierarquico disciplinar regulamentar de policia",
    orderIndex: 5,
    weight: 1.2,
  },
  {
    id: "admin_t6",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 06",
    title: "Atos administrativos.",
    normalizedTitle: "atos administrativos requisitos atributos classificacao especies extincao invalidez",
    orderIndex: 6,
    weight: 1.2,
  },
  {
    id: "admin_t7",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 07",
    title: "Licitações e Contratos Administrativos. Lei nº 14.133/2021 — licitações parte 1.",
    normalizedTitle: "licitacoes contratos lei 14133 2021 parte 1",
    orderIndex: 7,
    weight: 1.2,
  },
  {
    id: "admin_t8",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 08",
    title: "Licitações e Contratos Administrativos. Lei nº 14.133/2021 — licitações parte 2.",
    normalizedTitle: "licitacoes contratos lei 14133 2021 parte 2",
    orderIndex: 8,
    weight: 1.2,
  },
  {
    id: "admin_t9",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 09",
    title: "Licitações e Contratos Administrativos — contratos.",
    normalizedTitle: "licitacoes contratos administrativos",
    orderIndex: 9,
    weight: 1.2,
  },
  {
    id: "admin_t10",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 10",
    title: "Serviços públicos. Lei nº 8.987/1995.",
    normalizedTitle: "servicos publicos lei 8987 1995 concessao permissao autorizacao",
    orderIndex: 10,
    weight: 1.2,
  },
  {
    id: "admin_t11",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 11",
    title: "PPPs, consórcios públicos e consórcios administrativos.",
    normalizedTitle: "ppps parcerias publico privadas consorcios publicos consorcios administrativos",
    orderIndex: 11,
    weight: 1.2,
  },
  {
    id: "admin_t12",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 12",
    title: "Convênios e instrumentos congêneres.",
    normalizedTitle: "convenios instrumentos congeneres",
    orderIndex: 12,
    weight: 1.2,
  },
  {
    id: "admin_t13",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 13",
    title: "Controle da Administração Pública.",
    normalizedTitle: "controle da administracao publica administrativo judicial legislativo",
    orderIndex: 13,
    weight: 1.2,
  },
  {
    id: "admin_t14",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 14",
    title: "Responsabilidade civil do Estado.",
    normalizedTitle: "responsabilidade civil do estado objetiva subjetiva regressiva",
    orderIndex: 14,
    weight: 1.2,
  },
  {
    id: "admin_t15",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 15",
    title: "Bens públicos.",
    normalizedTitle: "bens publicos classificacao afetacao desafetacao aquisicao alienacao",
    orderIndex: 15,
    weight: 1.2,
  },
  {
    id: "admin_t16",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 16",
    title: "Intervenção do Estado na propriedade.",
    normalizedTitle: "intervencao do estado na propriedade desapropriacao tombamento servidao ocupacao requisicao",
    orderIndex: 16,
    weight: 1.2,
  },
  {
    id: "admin_t17",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 17",
    title: "Agentes públicos.",
    normalizedTitle: "agentes publicos cargos empregos funcoes publicas lei 8112",
    orderIndex: 17,
    weight: 1.2,
  },
  {
    id: "admin_t18",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 18",
    title: "Processo administrativo. Lei nº 9.784/1999.",
    normalizedTitle: "processo administrativo lei 9784 1999",
    orderIndex: 18,
    weight: 1.2,
  },
  {
    id: "admin_t19",
    subjectName: "Direito Administrativo",
    topicCode: "Tópico 19",
    title: "Improbidade administrativa. Lei nº 8.429/1992.",
    normalizedTitle: "improbidade administrativa lei 8429 1992",
    orderIndex: 19,
    weight: 1.2,
  },

  // DIREITO CONSTITUCIONAL
  {
    id: "const_t0",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 00",
    title: "Conceitos introdutórios. Classificação e aplicabilidade das normas.",
    normalizedTitle: "conceitos introdutorios principios fundamentais classificacao das constituicoes aplicabilidade interpretacao vigencia eficacia",
    orderIndex: 0,
    weight: 1.2,
  },
  {
    id: "const_t1",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 01",
    title: "Teoria geral dos direitos fundamentais.",
    normalizedTitle: "teoria geral dos direitos fundamentais",
    orderIndex: 1,
    weight: 1.2,
  },
  {
    id: "const_t2",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 02",
    title: "Direitos e deveres individuais e coletivos — Parte I.",
    normalizedTitle: "direitos deveres individuais coletivos parte 1 artigo 5",
    orderIndex: 2,
    weight: 1.2,
  },
  {
    id: "const_t3",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 03",
    title: "Direitos e deveres individuais e coletivos — Parte II.",
    normalizedTitle: "direitos deveres individuais coletivos parte 2",
    orderIndex: 3,
    weight: 1.2,
  },
  {
    id: "const_t4",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 04",
    title: "Direitos sociais.",
    normalizedTitle: "direitos sociais trabalhadores",
    orderIndex: 4,
    weight: 1.2,
  },
  {
    id: "const_t5",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 05",
    title: "Nacionalidade.",
    normalizedTitle: "nacionalidade nato naturalizado",
    orderIndex: 5,
    weight: 1.2,
  },
  {
    id: "const_t6",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 06",
    title: "Direitos políticos.",
    normalizedTitle: "direitos politicos elegibilidade",
    orderIndex: 6,
    weight: 1.2,
  },
  {
    id: "const_t7",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 07",
    title: "Partidos políticos.",
    normalizedTitle: "partidos politicos autonomias",
    orderIndex: 7,
    weight: 1.2,
  },
  {
    id: "const_t8",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 08",
    title: "Organização político-administrativa.",
    normalizedTitle: "organizacao politico administrativa uniao estados distrito federal municipios",
    orderIndex: 8,
    weight: 1.2,
  },
  {
    id: "const_t9",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 09",
    title: "Administração Pública. Servidores públicos.",
    normalizedTitle: "administracao publica principios constituicionais servidores publicos",
    orderIndex: 9,
    weight: 1.2,
  },
  {
    id: "const_t10",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 10",
    title: "Poder Legislativo.",
    normalizedTitle: "poder legislativo congresso camara senado tribunal de contas",
    orderIndex: 10,
    weight: 1.2,
  },
  {
    id: "const_t11",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 11",
    title: "Processo Legislativo. Reforma Constitucional.",
    normalizedTitle: "processo legislativo reforma constitucional emendas",
    orderIndex: 11,
    weight: 1.2,
  },
  {
    id: "const_t12",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 12",
    title: "Poder Executivo.",
    normalizedTitle: "poder executivo presidente da republica ministros de estado atribuicoes responsabilidades",
    orderIndex: 12,
    weight: 1.2,
  },
  {
    id: "const_t13",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 13",
    title: "Poder Judiciário.",
    normalizedTitle: "poder judiciario disposicoes gerais stf stj tst trt tribunais",
    orderIndex: 13,
    weight: 1.2,
  },
  {
    id: "const_t14",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 14",
    title: "Funções essenciais à Justiça.",
    normalizedTitle: "funcoes essenciais justica ministerio publico defensoria advocacia publica",
    orderIndex: 14,
    weight: 1.2,
  },
  {
    id: "const_t15",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 15",
    title: "Ordem Social.",
    normalizedTitle: "ordem social seguridade educacao saude cultura",
    orderIndex: 15,
    weight: 1.2,
  },
  {
    id: "const_t16",
    subjectName: "Direito Constitucional",
    topicCode: "Tópico 16",
    title: "Controle de Constitucionalidade.",
    normalizedTitle: "controle de constitucionalidade concentrado difuso adi adc adpf",
    orderIndex: 16,
    weight: 1.2,
  },

  // DIREITO DO TRABALHO (PESO MÁXIMO)
  {
    id: "work_t1",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 01",
    title: "Princípios e fontes do Direito do Trabalho. Direitos Constitucionais dos Trabalhadores. Renúncia e transação.",
    normalizedTitle: "principios fontes do direito do trabalho constitucionais trabalhadores renuncia transacao",
    orderIndex: 1,
    weight: 2.0,
  },
  {
    id: "work_t2",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 02",
    title: "Relações de trabalho e emprego. Empregado. Empregador.",
    normalizedTitle: "relacoes de trabalho emprego empregado empregador caracteristicas",
    orderIndex: 2,
    weight: 2.0,
  },
  {
    id: "work_t3",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 03",
    title: "Terceirização trabalhista.",
    normalizedTitle: "terceirizacao trabalhista atividade fim meio responsabilidade",
    orderIndex: 3,
    weight: 2.0,
  },
  {
    id: "work_t4",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 04",
    title: "Contrato de trabalho. Alteração, suspensão e interrupção. Poderes do empregador.",
    normalizedTitle: "contrato de trabalho alteracao suspensao interrupcao poderes do empregador",
    orderIndex: 4,
    weight: 2.0,
  },
  {
    id: "work_t5",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 05",
    title: "Término do contrato de trabalho. Aviso prévio. Garantias provisórias de emprego.",
    normalizedTitle: "termino do contrato de trabalho aviso previo garantias provisorias estabilidade",
    orderIndex: 5,
    weight: 2.0,
  },
  {
    id: "work_t6",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 06",
    title: "Jornada de trabalho e descansos.",
    normalizedTitle: "jornada de trabalho descansos intervalos horas extras",
    orderIndex: 6,
    weight: 2.0,
  },
  {
    id: "work_t7",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 07",
    title: "Remuneração e salário. Equiparação salarial.",
    normalizedTitle: "remuneracao salario equiparacao salarial parcelas salariais",
    orderIndex: 7,
    weight: 2.0,
  },
  {
    id: "work_t8",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 08",
    title: "Férias. Prescrição e decadência.",
    normalizedTitle: "ferias prescricao decadencia bienal quinquenal",
    orderIndex: 8,
    weight: 2.0,
  },
  {
    id: "work_t9",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 09",
    title: "Segurança e Saúde do Trabalho. CIPA. Trabalho do menor e da mulher.",
    normalizedTitle: "seguranca saude do trabalho cipa menor mulher",
    orderIndex: 9,
    weight: 2.0,
  },
  {
    id: "work_t10",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 10",
    title: "Comissões de Conciliação Prévia. Direito Coletivo do Trabalho.",
    normalizedTitle: "comissoes de conciliacao previa direito coletivo do trabalho acordos convencoes coletivas",
    orderIndex: 10,
    weight: 2.0,
  },
  {
    id: "work_t11",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 11",
    title: "FGTS.",
    normalizedTitle: "fgts fundo de garantia tempo servico depositos saques",
    orderIndex: 11,
    weight: 2.0,
  },
  {
    id: "work_t12",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 12",
    title: "Sindicatos. Greve.",
    normalizedTitle: "sindicatos greve direito a greve limitacoes",
    orderIndex: 12,
    weight: 2.0,
  },
  {
    id: "work_t13",
    subjectName: "Direito do Trabalho",
    topicCode: "Tópico 13",
    title: "Trabalho doméstico.",
    normalizedTitle: "trabalho domestico lei complementar 150",
    orderIndex: 13,
    weight: 2.0,
  },

  // DIREITO CIVIL
  {
    id: "civil_t0",
    subjectName: "Direito Civil",
    topicCode: "Tópico 00",
    title: "Lei de Introdução às Normas do Direito Brasileiro.",
    normalizedTitle: "lindb lei de introducao normas do direito brasileiro vigencia eficacia leis",
    orderIndex: 0,
    weight: 1.0,
  },
  {
    id: "civil_t1",
    subjectName: "Direito Civil",
    topicCode: "Tópico 01",
    title: "Pessoas naturais.",
    normalizedTitle: "pessoas naturais personalidade capacidade emancipacao ausencia morte",
    orderIndex: 1,
    weight: 1.0,
  },
  {
    id: "civil_t2",
    subjectName: "Direito Civil",
    topicCode: "Tópico 02",
    title: "Pessoas jurídicas.",
    normalizedTitle: "pessoas juridicas associacoes fundacoes desconsideracao personalidade",
    orderIndex: 2,
    weight: 1.0,
  },
  {
    id: "civil_t3",
    subjectName: "Direito Civil",
    topicCode: "Tópico 03",
    title: "Bens.",
    normalizedTitle: "bens moveis imoveis fungiveis consumiveis publicos",
    orderIndex: 3,
    weight: 1.0,
  },
  {
    id: "civil_t4",
    subjectName: "Direito Civil",
    topicCode: "Tópico 04",
    title: "Fatos jurídicos.",
    normalizedTitle: "fatos juridicos negocios juridicos validade defeitos erros dolo coacao fraude",
    orderIndex: 4,
    weight: 1.0,
  },
  {
    id: "civil_t5",
    subjectName: "Direito Civil",
    topicCode: "Tópico 05",
    title: "Atos jurídicos.",
    normalizedTitle: "atos juridicos lícitos ilicitos",
    orderIndex: 5,
    weight: 1.0,
  },
  {
    id: "civil_t6",
    subjectName: "Direito Civil",
    topicCode: "Tópico 06",
    title: "Prescrição e decadência.",
    normalizedTitle: "prescricao decadencia prazos civil",
    orderIndex: 6,
    weight: 1.0,
  },
  {
    id: "civil_t7",
    subjectName: "Direito Civil",
    topicCode: "Tópico 07",
    title: "Direito das obrigações — Parte I.",
    normalizedTitle: "direito das obrigacoes parte 1 dar fazer nao fazer solidarias",
    orderIndex: 7,
    weight: 1.0,
  },
  {
    id: "civil_t8",
    subjectName: "Direito Civil",
    topicCode: "Tópico 08",
    title: "Direito das obrigações — Parte II.",
    normalizedTitle: "direito das obrigacoes parte 2 adimplemento inadimplemento perdas danos",
    orderIndex: 8,
    weight: 1.0,
  },
  {
    id: "civil_t9",
    subjectName: "Direito Civil",
    topicCode: "Tópico 09",
    title: "Teoria geral dos contratos.",
    normalizedTitle: "teoria geral dos contratos principios interpretacao",
    orderIndex: 9,
    weight: 1.0,
  },
  {
    id: "civil_t10",
    subjectName: "Direito Civil",
    topicCode: "Tópico 10",
    title: "Responsabilidade civil.",
    normalizedTitle: "responsabilidade civil dano nexo causalidade culpa objetiva subjetiva",
    orderIndex: 10,
    weight: 1.0,
  },
  {
    id: "civil_t11",
    subjectName: "Direito Civil",
    topicCode: "Tópico 11",
    title: "Posse e propriedade.",
    normalizedTitle: "posse propriedade aquisicao perda usucapiao",
    orderIndex: 11,
    weight: 1.0,
  },
  {
    id: "civil_t12",
    subjectName: "Direito Civil",
    topicCode: "Tópico 12",
    title: "Direitos reais.",
    normalizedTitle: "direitos reais superficie usufruto hipoteca alienacao fiduciaria",
    orderIndex: 12,
    weight: 1.0,
  },

  // DIREITO PROCESSUAL CIVIL
  {
    id: "proc_civil_t0",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 00",
    title: "Normas Fundamentais do Processo Civil.",
    normalizedTitle: "normas fundamentais do processo civil principios cpc",
    orderIndex: 0,
    weight: 1.0,
  },
  {
    id: "proc_civil_t1",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 01",
    title: "Jurisdição e Ação.",
    normalizedTitle: "jurisdicao acao elementos condicoes",
    orderIndex: 1,
    weight: 1.0,
  },
  {
    id: "proc_civil_t2",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 02",
    title: "Competência.",
    normalizedTitle: "competencia absoluta relativa territorial valor",
    orderIndex: 2,
    weight: 1.0,
  },
  {
    id: "proc_civil_t3",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 03",
    title: "Sujeitos Processuais: Partes e Procuradores. Litisconsórcio e Intervenção de terceiros.",
    normalizedTitle: "sujeitos processuais partes procuradores litisconsorcio intervencao terceiros",
    orderIndex: 3,
    weight: 1.0,
  },
  {
    id: "proc_civil_t4",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 04",
    title: "Sujeitos Processuais: Juízes, Auxiliares da Justiça, Ministério Público, Defensoria Pública e Advocacia Pública.",
    normalizedTitle: "sujeitos processuais juizes auxiliares da justica ministerio publico defensoria advocacia",
    orderIndex: 4,
    weight: 1.0,
  },
  {
    id: "proc_civil_t5",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 05",
    title: "Atos Processuais.",
    normalizedTitle: "atos processuais tempo lugar prazos forma",
    orderIndex: 5,
    weight: 1.0,
  },
  {
    id: "proc_civil_t6",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 06",
    title: "Comunicação dos Atos Processuais, Nulidade, Valor da Causa, Distribuição e Registro.",
    normalizedTitle: "comunicacao atos processuais nulidade valor da causa distribuicao registro",
    orderIndex: 6,
    weight: 1.0,
  },
  {
    id: "proc_civil_t7",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 07",
    title: "Tutela Provisória.",
    normalizedTitle: "tutela provisoria urgencia evidencia cautelar antecipada",
    orderIndex: 7,
    weight: 1.0,
  },
  {
    id: "proc_civil_t8",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 08",
    title: "Formação, Suspensão e Extinção do Processo. Procedimento comum até o saneamento.",
    normalizedTitle: "formacao suspensao extincao do processo procedimento comum saneamento peticao inicial",
    orderIndex: 8,
    weight: 1.0,
  },
  {
    id: "proc_civil_t9",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 09",
    title: "Provas — parte 01.",
    normalizedTitle: "provas parte 1 teoria geral depoimento confissao documentos",
    orderIndex: 9,
    weight: 1.0,
  },
  {
    id: "proc_civil_t10",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 10",
    title: "Provas — parte 02.",
    normalizedTitle: "provas parte 2 testemunhal pericial inspecao judicial",
    orderIndex: 10,
    weight: 1.0,
  },
  {
    id: "proc_civil_t11",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 11",
    title: "Sentença, Coisa Julgada, Liquidação e Cumprimento de Sentença.",
    normalizedTitle: "sentenca coisa julgada liquidacao cumprimento de sentenca",
    orderIndex: 11,
    weight: 1.0,
  },
  {
    id: "proc_civil_t12",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 12",
    title: "Processo de Execução.",
    normalizedTitle: "processo de execucao titulos judiciais extrajudiciais embargos",
    orderIndex: 12,
    weight: 1.0,
  },
  {
    id: "proc_civil_t13",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 13",
    title: "Procedimentos Especiais — parte 01.",
    normalizedTitle: "procedimentos especiais parte 1 consignacao em pagamento possessorias",
    orderIndex: 13,
    weight: 1.0,
  },
  {
    id: "proc_civil_t14",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 14",
    title: "Procedimentos Especiais — parte 02.",
    normalizedTitle: "procedimentos especiais parte 2 inventario partilha monitoria",
    orderIndex: 14,
    weight: 1.0,
  },
  {
    id: "proc_civil_t15",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 15",
    title: "Meios de Impugnação das Decisões Judiciais.",
    normalizedTitle: "meios de impugnacao das decisoes judiciais cpc",
    orderIndex: 15,
    weight: 1.0,
  },
  {
    id: "proc_civil_t16",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 16",
    title: "Recursos em Espécie.",
    normalizedTitle: "recursos em especie apelacao agravos embargos declaracao especial extraordinario",
    orderIndex: 16,
    weight: 1.0,
  },
  {
    id: "proc_civil_t17",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 17",
    title: "Ação Popular, Ação Civil Pública, Mandado de Segurança, Mandado de Injunção, Habeas Data.",
    normalizedTitle: "acao popular acao civil publica mandado seguranca injuncao habeas data",
    orderIndex: 17,
    weight: 1.0,
  },
  {
    id: "proc_civil_t18",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 18",
    title: "Processo Civil nos sistemas de controle da constitucionalidade e ações constitucionais.",
    normalizedTitle: "processo civil sistemas controle constitucionalidade acoes constitucionais",
    orderIndex: 18,
    weight: 1.0,
  },
  {
    id: "proc_civil_t19",
    subjectName: "Direito Processual Civil",
    topicCode: "Tópico 19",
    title: "Processo Judicial Eletrônico. Lei nº 11.419/2006.",
    normalizedTitle: "processo judicial eletronico lei 11419 2006",
    orderIndex: 19,
    weight: 1.0,
  },

  // DIREITO PROCESSUAL DO TRABALHO (PESO MÁXIMO)
  {
    id: "proc_work_t0",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 00",
    title: "Teoria geral do processo do trabalho. Princípios e organização da Justiça do Trabalho.",
    normalizedTitle: "teoria geral processo do trabalho principios organizacao da justica do trabalho",
    orderIndex: 0,
    weight: 2.0,
  },
  {
    id: "proc_work_t1",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 01",
    title: "Competência da Justiça do Trabalho.",
    normalizedTitle: "competencia da justica do trabalho material territorial funcional",
    orderIndex: 1,
    weight: 2.0,
  },
  {
    id: "proc_work_t2",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 02",
    title: "Serviços Auxiliares da Justiça do Trabalho. Partes e Procuradores. Ministério Público.",
    normalizedTitle: "servicos auxiliares justica do trabalho partes procuradores ministerio publico jus postulandi",
    orderIndex: 2,
    weight: 2.0,
  },
  {
    id: "proc_work_t3",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 03",
    title: "Prazos processuais. Custas. Nulidades processuais. Petição inicial.",
    normalizedTitle: "prazos processuais custas nulidades peticao inicial trabalhista",
    orderIndex: 3,
    weight: 2.0,
  },
  {
    id: "proc_work_t4",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 04",
    title: "Notificação do reclamado. Resposta do réu. Revelia.",
    normalizedTitle: "notificacao reclamado resposta do reu revelia contestacao reconvencao excecoes",
    orderIndex: 4,
    weight: 2.0,
  },
  {
    id: "proc_work_t5",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 05",
    title: "Audiência. Provas. Sentença. Coisa julgada. Rito sumário e sumaríssimo.",
    normalizedTitle: "audiencia provas sentenca coisa julgada rito sumario sumarissimo instrucao julgamento",
    orderIndex: 5,
    weight: 2.0,
  },
  {
    id: "proc_work_t6",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 06",
    title: "Recursos no processo do trabalho — teoria geral e recursos em espécie.",
    normalizedTitle: "recursos processo trabalho teoria geral recursos especie ordinario revista agravos embargos tst",
    orderIndex: 6,
    weight: 2.0,
  },
  {
    id: "proc_work_t7",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 07",
    title: "Liquidação de sentença e processo de execução.",
    normalizedTitle: "liquidacao de sentenca processo de execucao calculos embargos penhora",
    orderIndex: 7,
    weight: 2.0,
  },
  {
    id: "proc_work_t8",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 08",
    title: "Procedimentos especiais trabalhistas.",
    normalizedTitle: "procedimentos especiais trabalhistas consignacao inquerito apuracao falta grave",
    orderIndex: 8,
    weight: 2.0,
  },
  {
    id: "proc_work_t9",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 09",
    title: "Dissídio coletivo de trabalho e ação de cumprimento.",
    normalizedTitle: "dissidio coletivo trabalho acao de cumprimento",
    orderIndex: 9,
    weight: 2.0,
  },
  {
    id: "proc_work_t10",
    subjectName: "Direito Processual do Trabalho",
    topicCode: "Tópico 10",
    title: "Processo Judicial Eletrônico.",
    normalizedTitle: "processo judicial eletronico pje trabalhista",
    orderIndex: 10,
    weight: 2.0,
  },
];
